### ISSUE TITLE
PID Loop Modeling Clarification

### ISSUE THREAD

**Issue by PaulBricknell** [google/digitalbuildings#131]
Looking for additional MQTT Datapoint name (descriptors, etc) for the following  (BMS points) Internal PID loop Variables for AHU, FCU, PACU. There is no current sub fields for say Proportional, Integral, Derivative gain values.

BMS Point name:
Zone Temp HTG PID P gain
Zone Temp HTG PID I gain
Zone Temp HTG PID D gain
Zone Temp HTG PID Interval
Zone Temp CLG PID P gain
Zone Temp CLG PID I gain
Zone Temp CLG PID D gain
Zone Temp CLG PID Interval

Thanks

**Comment by jcbrough** [comment]
Hi Paul,

What is your use case for exposing these settings to the IoT?

Just interested as these properties might be consider as internal working parameters and not 'of interest' at the Cloud level.

But I can see that as this develops these settings might be interesting to Analytical engines. Of course they could always be accessed via AV Objects (in BACnet) where needed and the BMS SIs instructed to make them accessible.
________________________________

**Comment by PaulBricknell** [comment]
Hi John,
The use case is for UI read only per specification.  The values are already available in BACnet on local BMS.
The project I can see has several FCU and PAC type units, all similar in functionality. So we could look into further analytic rules to assist in loop tuning, unit performance comparisons.

**Comment by tasodorff** [comment]
We don't have `proportional`, `integral`, or `derivative` yet but the ontology could support it (likely as a `measurement_descriptor`. The only question I would have about this is what form the I and D gains come in. There are two standard ways of PID control that I know of, one where all the parameters (P, I, and D) are dimensionless gains, and alternately where P is a gain and I and D are time values (integration time and derivative time). We can model both, but would want to be clear on the units for the dimensional case.

**Comment by berkoben** [comment]
Thinking aloud and working through an example, it's not as easy as it seems on face: 

```
damper_percentage_command
{proportional|integral|derivative}_damper_percentage_gain
```
is general (i.e. supports cases where measurement_descriptor is always used), but gain would have to become a point type. 
 It's also a sort of strange way of describing it because the gain is not actually on the damper percentage but the difference between flowrate sensor and setpoint.  Would it more correct as `proportional_discharge_flowrate_gain`?

**Comment by david-waterworth** [comment]
subfields.yaml defines both 'damper' and 'controller' as components, which I think makes sense in this case - the gain is an attribute of the controller not the damper itself (i.e. Haystack 4.0 has both equip and device, the damper is an equip and the controller a device). I'm not sure there's any need to specify percentage since I think it's really unitless - you're multiplying the difference between the setpoint and measurement by a value K.

So maybe `damper_controller_gain` would work - assuming there's only a single gain parameter, otherwise you may have to be more specific i.e. `damper_controller_error_gain`?

**Comment by berkoben** [comment]
@david-waterworth regarding percentage, the intent was to link the point representing the output `damper_percentage_command` to the loop parameters.  We have some point types (ex: `status`) where the measurement_type is not treated literally.  (ex: in the case of a status, the value is aways an enumeration).  

the more I think about it, the more I think the complete set of interactions needs something beyond the name to represent (i.e. some new relationship concept that we haven't created yet).  Given this, the choice that needs to made is which other point should be trivially associated by name.  the choices being:

"**damper_percentage**\_command"
"proportional_**damper_percentage**_gain"

"**discharge_air_flowrate**_sensor"
"**discharge_air_flowrate**\_setpoint"
"proportional\_**discharge_air_flowrate**[_difference]_gain"

Personally, the second option feels more self-descriptive.  Then there would need to be some separate construct to link the gain parameters to the output parameter

**Comment by mschulze17** [comment]
@tasodorff tagging you

**Comment by mschulze17** [comment]
@tasodorff bump on next steps for this Issue

**Comment by mschulze17** [comment]
Closing Issue, converting to Carson Backlog item
