### ISSUE TITLE
Scope of schema compared to IFC

### ISSUE THREAD

**Issue by Moult** [google/digitalbuildings#37]
This looks like an interesting project! I'm curious as to what is the intended scope, especially in contrast to existing schemas like IFC. As stated in the readme, it does borrow heavily from Brick schema, so perhaps mentioning how it plans to fit into the Brick ecosystem would be interesting too :)

**Comment by charbull** [comment]
Hi @Moult, we are preparing an alignment with Brick-Schema, to be released soon.

**Comment by Moult** [comment]
Thanks @charbull - what about IFC?

**Comment by charbull** [comment]
@Moult Not directly with IFC yet. However, an integration with BIM is possible.

**Comment by corymosiman12** [comment]
@charbull - additional question.  For the most part, Brick and Haystack haven't (to this point) utilized the ontology to provide what I would think of as 'templates', however, this project seems to have taken that on.  Additionally, the ontology appears to include aspects pertinent to the 'control intention' of a specific piece of equipment / etc.  Would you comment on your decisions / reasonings to include these two aspects?  They seem to be very useful!

**Comment by david-waterworth** [comment]
It seems though that this gets 'lost' when translating to RDF? i.e. an AHU may be composed of the ECONMD 'trait' but when the RDF is generated all the fields from the traits get unioned? It could be nice if they were retained so that in the final representation you can reflect on the type to infer what it supports. I suspect this would require different representations of the same object for different use cases though - i.e. an engineer would be interesting the control traits like ECONMD. As a data scientist, I'm more interested in which sensor sets are present (i.e. a chiller may have COP, or kWe and kWr meters allowing me to infer COP, or current, water flow and temps etc.).

**Comment by david-waterworth** [comment]
I really like both the composition of subfields - it's pretty much how we tag points as well. Also, the abstract class approach is really nice. I did try and represent a number of AHU's I have data for and found it quite difficult to decide which of the numerous AHU subclasses best represented the equipment though - it requires quite a lot more information about the plant than what you might get just from raw BACnet point data (I'm specifically interested in inferring the ontology from the BMS alone). But it's easy to create your own yaml - I created a simple version where I split into subclasses more along the haystack location approach (i.e. supply, return etc) and that worked quite well.

**Comment by tasodorff** [comment]
Hi David,

We are soon going to be releasing some tooling which will infer the closest AHU (or any other class) match to the ontology from a set of fields defined in a spreadsheet (i.e. from a properly formatted BMS export). Hopefully this will help with application.

In any event, the intention is that the any particular equipment type is built up from core functionality and available telemetry. Having some familiarity with `ABSTRACT` types is necessary for this, but once a user has comfortable recall for these, it is quite simple to pull abstract types out and assign them to individual devices. For example, a typical AHU with economizer, supply fan, static pressure control, supply temp control, chilled water control, and an exhaust fan controlling space pressure can be constructed from implementing `AHU`, `ECON`, `SFSS`, SFVSC` (for variable speed control), `SSPC`,  `CHWSC`, `EFSS`, `EFVSC`, and `BSPC`. Understanding this can be somewhat cumbersome to define net new, we are hoping some of the tooling will help with some of this.

**Comment by david-waterworth** [comment]
Yeah, tooling would definitely help. One challenge is to identify what really is typical as well, it seems that a typical Australian economiser is different to a US one for example (not just in spelling...). You have mixed_air_temperature_sensor as a "uses" but I don't encounter mixed air temperature sensors very often although most if not all of our buildings have an economy mode. What they do generally have is an economy temperature setpoint above which economy mode is disabled.

**Comment by tasodorff** [comment]
> Yeah, tooling would definitely help. One challenge is to identify what really is typical as well, it seems that a typical Australian economiser is different to a US one for example (not just in spelling...). You have mixed_air_temperature_sensor as a "uses" but I don't encounter mixed air temperature sensors very often although most if not all of our buildings have an economy mode. What they do generally have is an economy temperature setpoint above which economy mode is disabled. 

We support incomplete types, so in this example the economy mode you are describing would be `ECON` even though it's missing mixed air. 

We also have versions of econ control that have MAT and MATSTPT as part of their control style, which is distinct from econ controlling to the supply temp (or others that are commonly seen).

**Comment by berkoben** [comment]
> @charbull - additional question. For the most part, Brick and Haystack haven't (to this point) utilized the ontology to provide what I would think of as 'templates', however, this project seems to have taken that on. Additionally, the ontology appears to include aspects pertinent to the 'control intention' of a specific piece of equipment / etc. Would you comment on your decisions / reasonings to include these two aspects? They seem to be very useful!

@corymosiman12 fundamentally the objective of starting this project was to turn scale to our advantage in facilities management.  In the typical (non-templated) model, a portfolio gets increasingly unwieldy as it grows because it's very difficult to keep everything standardized, especially if you're global.  

With DBO, the idea was to find a way to abstract away the irrelevant differences between sites and focus on the similarities so that we can write applications that apply across the portfolio.  Templates are critical because they not only help people map to consistent models, but eventually the inform design - for instance if we don't like pressure dependent VAVs and the model set we expose to our mechanical designer doesn't include them, then they have to come ask the question "where's the pressure dependent VAV model?" and we say "bad designer!  No pressure dependent VAVs!".   

The "control-intent" focus was a practical choice.  I want to model something because I want to DO something with it: analyze if it's working as intended, change its behavior, turn it on and off, etc.  As a result, focusing the model around composable functional groups just made sense.

**Comment by mschulze17** [comment]
Closed per review with Trevor
