### ISSUE TITLE
Bayview domestic water systems (DWST) with water to water, water source heat pumps

### ISSUE THREAD

**Issue by tom-skoczylas** [google/digitalbuildings#520]
**Problem**
The domestic water systems for the Bayview buildings have domestic water systems (DWST), each with two water to water, water source heat pumps. The available points are the heat pump enable, hot potable leaving hot water temperature sensor, and a common potable hot leaving water temperature setpoint, as indicated in screenshot below. 

**Screenshot**
![BV100_DWST_WSHPs](https://user-images.githubusercontent.com/86078522/160913909-0d0d98bc-2b98-4080-a0d5-53b0c7ffea36.png)

**Solution**
A noncanonical/one-off DWST equipment type was created (DWST_SWTC_CPVSC2X_WSHP2X) with the heat pump points added to uses as follows.

DWST_SWTC_CPVSC2X_WSHP2X:
  description: "Non-standard domestic water system with 2 circulation pumps and 2 water-source heat pumps.
  The potable leaving water temperature is for the water leaving the heat pumps and the heat pumps share a
  common setpoint."
  is_canonical: false
  implements:
  - DWST
  - SWTC
  - CPVSC2X
  uses:
  - compressor_run_command_1
  - compressor_run_command_2
  - potable_hot_leaving_water_temperature_sensor_1
  - potable_hot_leaving_water_temperature_sensor_2
  - potable_hot_leaving_water_temperature_setpoint

**Comment by tasodorff** [comment]
@tom-skoczylas think we've discussed this, and im fine with this as a one off for now. please add a TODO comment above the device for us to go remove this thing if we get more examples of such a water-to-water heat pump; might also be worth us discussing internally what this device should be called, because HP is technically correct but we generally consider them to be airside devices. we would need to differentiate between airside and waterside devices if this is more than a one-off.
