### ISSUE TITLE
Building_Air_Static_Pressure_Sensor

### ISSUE THREAD

**Issue by aidan-parkinson** [google/digitalbuildings#54]
I apologies if my contributions so far have not been received well. It was my intention to make a constructive contribution, but I think I have made some mistakes with the way I have engaged with this so far.

digitalbuildings/ontology/yaml/resources/subfields/subfields.yaml

line 50 - `building: "Applies to the entire building or group of zones within building (e.g. Building_Air_Static_Pressure_Sensor)"`

In the case of  a "Building_Air_Static_Pressure_Sensor", I assume this tag means the static pressure of the index run ductwork supplying fresh air to the building. I assume it's not a weighted average of static pressures within the building itself, nor a group (perhaps an array?) of static pressures for each zone within the building. If I am correct here, the terms "index run" and "fresh air" would also need defining.

**Comment by tasodorff** [comment]
No worries on the contribution comments; from what I've seen of your comments so far we just need more specificity in the feedback. 

For building_air_static_pressure_sensor, the intended usage is as a building level pressure sensor (i.e. represents the static in the building); for duct static, the field supply_air_static_pressure_sensor is the common usage (most AHU types use this, for instance). The concept of discharge_air_static_pressure_sensor is also available, but is not normally used (the usages I've seen are where the pressure replaces status CTs for fan proofs... there is no use case for pressure control in an open duct).

Index run would refer to duct static on a portion of the primary duct (i.e. not a branch); we don't have a subfield currently defined to indicate a primary versus secondary duct, since it usually isn't necessary. Open to adding it, if you have a particular use case we can use to concretely model it.

Fresh air exists in the ontology as outside air. Note that the subfields tend to follow American standard names (we use exhaust, whereas the UK and other parts of the world substitute the term extract). @charbull do we have a plan to support synonyms?

**Comment by aidan-parkinson** [comment]
I'm sorry. I don't understand how it's possible to have a building level pressure sensor in the space. This would imply that there was no air movement or temperature variation in the building. Seems practically implausible to me.

Please be mindful, that from my perspective, when we talk about an Ontology of Digital Buildings I am looking for rigour in the domain knowledge base. The semantics require precision. This is what an Ontology means to me. I'm unlikely to accept a pragmatically tagged model, however inspiring it is. This was my original argument.

**Comment by tasodorff** [comment]
It is quite common to have building pressure sensors that aren't zone specific, but rather serve as a reference for the entire building. Not all buildings have zone specific pressure sensing; many older, smaller buildings have one sensor they use to coordinate control. Duly noted on the implication; it is sadly a reality of HVAC controls.
