### ISSUE TITLE
setpoint

### ISSUE THREAD

**Issue by aidan-parkinson** [google/digitalbuildings#55]
https://github.com/google/digitalbuildings/blob/master/ontology/yaml/resources/subfields/subfields.yaml

line 215 - `setpoint: "Control target of process or system."`

Although Wikipedia and the Collins English Dictionary might suggest otherwise. I believe the tag "setpoint" relates to the English phrase "set-point" as it relates to a target quantity that has been set for a controlled variable.

**Comment by tasodorff** [comment]
@aidan-parkinson not sure I understand the objection.

From Wikipedia: "a setpoint (also set point or set-point) is the desired or target value for an essential variable, or process value of a system". Our definition of setpoint as "control target for a process or system" seems in line with that.

**Comment by aidan-parkinson** [comment]
So, I think it's arguable in an Ontology that the term `setpoint` is not a proper use of English here - being a concatenation of a term that implies the tennis meaning.

I believe `set-point` has more of a rigorous foundation from an Ontological perspective. This is because the words `set` and `point` are found in every English dictionary I have looked at, and when used together in this way would seemingly infer what I think you intend.

**Comment by tasodorff** [comment]
we do not explicitly ban concatenation. we use it for terms like `specificenthalpy`, and it can be used sparingly to encode certain concepts atomically. in general, we look to avoid these types of things, but can support them as edge cases arise.

That being said, `setpoint` is such a ubiquitous term that it is probably fine as a single field. I don't find the dictionary argument to be a compelling one because we are not bound to someone else's definition for what any of our terms mean; we define them internally to the ontology. There are many terms that exist in this ontology which have meanings other than those you might find in a dictionary, or in the lexicon of other domains of knowledge. This is why we attempt to define them specifically here. 

If this is still something you'd like us to consider, please add it to the discussion for this repo. This isn't technically an issue.

**Comment by aidan-parkinson** [comment]
The underlying issue is how widely this Ontology will be recognised by the community. Presently, I don't recognise this definition of setpoint - neither does the Oxford English Dictionary. The noun `set point` and it's concatenated form is used in sports.

I'm not sure what the point is of releasing a project open-source in this manner if you intend it to be rejected outright by domain experts? Nor, improved upon by the wider community.

This is is my argument all along. This project is a model that is understandable by a very small group of biased agents. It's not a rigourous ontology that can be shared and understood by others. It seems this work will have to be done separately. I appreciate your efforts in creating this model and think it is inspiring. But I am not intending to use it as a reference for any ontology of mine!

**Comment by charbull** [comment]
@aidan-parkinson this project terminology is for HVAC domain experts.
I would like to close this thread as it is not really an issue more of a discussion.

Please send your questions at google-digital-building-discuss@googlegroups.com

Thank you.

**Comment by tasodorff** [comment]
Merriam Webster, Macmillan, Collins, Dictionary.com, and Wikipedia all define setpoint outside of a tennis setting. Collins specifically defines it as follows: _"(Mechanical engineering: Control, instrumentation and metrology) A setpoint is a state that a control system is aiming to reach."_ 

Our hope is that domain experts will use it and provide constructive feedback. Considering it was largely assembled by people with domain expertise, particularly in mechanical engineering and building controls, we think most of the terms will be well-understood... even `setpoint`. 

As @charbull mentioned, lets migrate this to a discussion.
