### ISSUE TITLE
Kelvin

### ISSUE THREAD

**Issue by aidan-parkinson** [google/digitalbuildings#65]
Please could you describe the unit `Kelvin` and why this is tagged as `standard`?

**Comment by tasodorff** [comment]
See here: http://qudt.org/vocab/unit/K.html

Please see the docs for information on this: 

_"While the current ontology configuration does not explicitly call out conversion factors, it generally tries to conform to unit names from QUDT so that their conversion factors can be used. Future development may integrate a unit ontology more directly."_

_"Under each subfield name, the configuration defines a list of dimensional units of a single Quantity Kind, One of the listed units must be listed as the STANDARD unit for the type. All of the STANDARD units for all subfields must belong to the same unit family, such as standard SI units."_
