### ISSUE TITLE
Running DBO instance validation has error on all points declared as MISSING in translation

### ISSUE THREAD

**Issue by josephedwardchang** [google/digitalbuildings#852]
**Description**
Running the latest DBO telemetry validation and it stopped with an unusual error. All of the points having MISSING declared in translation is giving error and halting the validation. The error is a vague: "[ERROR] Something failed during validation and has terminated validation. See logs above and error here: '/phase1_phase2_line_voltage_sensor_7'." Here the point: 'phase1_phase2_line_voltage_sensor_7' is an extra for our device (so I declared it as MISSING in translation). 

Since I don't know how this came to be error, I modified my DBO to have it declared under opt_uses just so I could continue. Then again, running the validator halted on another point declared as MISSING in translation. I repeated that, went through validation again and another halt on error at a point having the same declaration as MISSING in translation.

Is there a new rule on using MISSING, or maybe this is a bug perhaps? I noticed there were updates. Last month this was working ok.

**To Reproduce**
1. In any DBO entity (e.g., EM_PWM_PVCM) pick one field under "uses:", say, reactive_energy_accumulator
2. In your config.yaml declare the links for the device
3. In config.yaml under translation, set reactive_energy_accumulator as MISSING
4. Run validation tool, unknown error will be on reactive_energy_accumulator

**Expected behavior**
The telemetry validation will run through and validate everything without halting validation on error.

**Screenshots**
This is all working in previous version (i don't know which update caused this possible bug, sorry)
![image](https://user-images.githubusercontent.com/21256796/206070724-963b1361-475d-4672-9664-637d8a400e8c.png)

**OS:**
Linux box is WSL v1.0 running Ubuntu 20.04 under Windows 10 x64 Pro

**Additional context**

**Comment by trav3711** [comment]
Hey @josephedwardchang , this definitely a bug! Is it only telemetry validation that fails, or is it both telemetry and instance validation that fail? Can you provide me with an example input or just an entity block along with a screenshot of the error message?

**Comment by josephedwardchang** [comment]
Hi sir,
This was my error yesterday:
![image](https://user-images.githubusercontent.com/21256796/206331072-ec3fa197-1182-4d70-8617-9ba3702ba913.png)

I think this has now been fixed:
![image](https://user-images.githubusercontent.com/21256796/206331270-4fc0262e-7c93-48fe-9664-649adac99c80.png)

and it says: [WARNING]       Entity d5dfd697-9393-4ed7-b4b6-16b4b4008b34 (DDC-15) provides MISSING translation for field /damper_percentage_sensor_2 for a type PASSTHROUGH. This feature should only be used when the gateway cannot physically send required data and the virtual entity you are creating requires it. You must provide justification for all MISSING translations and that the applied virtual entity type is correct, otherwise your building config will be rejected.

But I don't understand: "when the gateway cannot physically send required data"... what I currently do when looking for devices in DBO, I find an almost similar one, say this MFSD which has extra fields that our device doesn't have. I will just use MISSING for those extra fields. With that warning now, it seems I would have to "create" a modified version of MFSD to have these extra fields removed and then use that instead of MFSD with MISSING points.

I guess this is what's required now?

**Comment by charbull** [comment]
@trav3711 @josephedwardchang I deleted the sample, such information must not be shared on github.
Thank you

**Comment by trav3711** [comment]
@josephedwardchang we patched a MISSING field's bug yesterday. Are you able to validate your config now or are you still getting a failure? @tasodorff should know something about having to extend the type.

**Comment by tasodorff** [comment]
@josephedwardchang to explain the warning:

missing fields are expected to be used only when you are modeling a device that controls a certain way, but the data is legitimately unavailable. lets look at two examples:

**Example 1:** say you have a `FAN_SS`, which requires `run_command` and `run_status`, but the fan you are integrating with does not make the `run_command` available for integration. However, you know that the device does is commanded to run by something in the system, but you simply cannot read that command. This is where you would use a `MISSING` field.

**Example 2:** say you have a `FAN_SS_VSC`, which requires `run_command`, `run_status`, and `speed_percentage_command`. However, upon inspection you find that the `speed_percentage_command` is not available because no VFD was installed -- therefore, there is no speed command to integrate with. In this instance, it would NOT be appropriate to model the device as `FAN_SS_VSC`, because it does not use `VSC` in its control; therefore, defining `speed_percentage_command` as `MISSING` would be inappropriate. 

The warning message is intended to draw your attention (and ours) to the uses of missing fields, to remind the users that missing fields are only supposed to be used in the scenario outlined in example 1.  We may ask you to justify why you chose to use missing fields when you submit a building config, to ensure they are being used appropriately. 

From the description you provided above, it sounds like you are properly using `MISSING` fields, **and there is no need to do anything differently in your modeling**.  You will continue to see warnings, but the warnings do not mean your building config is invalid. 

Please let me know if you have any questions, and we can discuss further.

**Comment by josephedwardchang** [comment]
Thank you sirs, I think we're good here (sorry for the sample i did). The fix and the explanation on when to use MISSING is well appreciated. Cheers,
